### PR TITLE
Revert iconv check executable related changes

### LINKED ISSUE #63: Boost.Locale don't build on macOS (missing iconv)
During build Boost.Locale, library iconv (which comes with Xcode) is not detected, so build Boost.Locale is skipped. This appeared in version 1.76 - in version 1.75 the build is successful.
```
Performing configuration checks
- default address-model    : 64-bit [1]
- default architecture     : x86 [1]
- has stat::st_mtim        : no [2]
- has stat::st_mtimensec   : no [2]
- has stat::st_mtimespec   : yes [2]
- has stat::st_birthtim    : no [2]
- has stat::st_birthtimensec : no [2]
- has stat::st_birthtimespec : yes [2]
- has statx                : no [2]
- has statx syscall        : no [2]
- has_icu builds           : no [2]
- iconv (libc)             : no [2]
- iconv (separate)         : no [2] <--this
- icu                      : no [2]
- icu (lib64)              : no [2]
- Boost.Locale needs either iconv or ICU library to be built.
- iconv (libc)             : no [3]
- iconv (separate)         : no [3] <--this
- icu                      : no [3]
- icu (lib64)              : no [3]
- Boost.Locale needs either iconv or ICU library to be built.
- lockfree boost::atomic_flag : no [2]
- compiler supports SSE2   : yes [2]
- compiler supports SSE4.1 : yes [2]
```

I also tried to install iconv separately with brew and pointed the path to it through `-sICONV_PATH.` But this did not give any results.

iMac2019
macOS 11.4 (20F71)
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0

### PR DESCRIPTION
**Pull request by TheSalvator**
fixes #63

### CODE REVIEW

**Comment by Flamefire** [comment]
Thanks for this! After discussion in Slack with @grafikrobot I created #107 which also fixes a similar issue with the ICU check. I also improved the naming and added comments on why the `obj` rule is required.

I'd suspect that the issue is only there when you pass `ICONV_PATH`, i.e. when you need an additional include path. Is that correct?

**Comment by TheSalvator** [comment]
@Flamefire Yep you can see it in here
https://c3i.jfrog.io/c3i/misc/logs/pr/12807/5-configs/macos-clang/boost/1.80.0//6dce47697105e9cab74f0925ce72b345cce34916-build.txt

`ICONV_PATH=/Users/jenkins/w/prod/BuildSingleReference@4/.conan/data/libiconv/1.17/_/_/package/0aa7be2d0914b6f3128105e305c90b9cb0cae86d`

Closing this one in favor of #107

**Comment by Flamefire** [comment]
I see thanks! Were you able to test #107 ? I don't have any system to actually test this and the Github OSX runners all have the iconv stuff in libc so the issue isn't reproducible there and hence I can't verify the fix.

**Comment by TheSalvator** [comment]
> I see thanks! Were you able to test #107 ? I don't have any system to actually test this and the Github OSX runners all have the iconv stuff in libc so the issue isn't reproducible there and hence I can't verify the fix.

Not yet, but today i'll do it)

**Pull request closed without merging**
